apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: twentycrm-server-pvc
  namespace: twentycrm
spec:
  volumeName: twentycrm-server-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
