apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: twentycrm-server
  name: twentycrm-server
  namespace: twentycrm
spec:
  serviceName: twentycrm-headless      # must exist (ClusterIP=None)
  replicas: 1
  selector:
    matchLabels:
      app: twentycrm-server
  template:
    metadata:
      annotations:
        linkerd.io/inject: "enabled"
      labels:
        app: twentycrm-server
    spec:
      containers:
        - name: twentycrm
          image: twentycrm/twenty:latest
          imagePullPolicy: Always
          env:
            - name: NODE_PORT
              value: "3000"
            - name: SIGN_IN_PREFILLED
              value: "false"
            - name: STORAGE_TYPE
              value: "local"
            - name: "ACCESS_TOKEN_EXPIRES_IN"
              value: "7d"
            - name: "LOGIN_TOKEN_EXPIRES_IN"
              value: "1h"
            - name: "PGUSER"
              valueFrom:
                secretKeyRef:
                  name: app.acid-app.credentials.postgresql.acid.zalan.do
                  key: username
            - name: "PGPASSWORD"
              valueFrom:
                secretKeyRef:
                  name: app.acid-app.credentials.postgresql.acid.zalan.do
                  key: password
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: tokens
                  key: accessToken
          envFrom:
            - configMapRef:
                name: twentycrm-env
          ports:
            - containerPort: 3000
              name: http-tcp
              protocol: TCP
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          stdin: true
          tty: true
          volumeMounts:
            - mountPath: /app/docker-data
              name: twentycrm-docker-data
            - mountPath: /app/packages/twenty-server/.local-storage
              name: twentycrm-server-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
  volumeClaimTemplates:
  - metadata:
      name: twentycrm-docker-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
  - metadata:
      name: twentycrm-server-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi