# This is a package for deploying the Twenty application using Kustomize.
# https://github.com/sozialhelden/twenty/tree/main/packages/twenty-docker/k8s/manifests
# https://twenty.com/developers/section/self-hosting


# The following resources are Sozialhelden e.V.-specific customizations
# for the Docker deployment.
#
# They add:
# - a custom PostgreSQL deployment
# - a custom Redis deployment
# - a custom CA + TLS setup for PostgreSQL

resources:
- ca-cert.yaml
- ca-issuer.yaml
- postgresql-certificate.yaml
- postgresql-database.yaml
- self-signed-issuer.yaml
- twentycrm-env.yaml
