apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: twentycrm-redis
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: twentycrm
  destination:
    namespace: twentycrm
    name: do-fra1-sozialhelden-production-fra1
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 16.9.7
    chart: redis
    helm:
      parameters:
      - name: 'master.persistence.size'
        value: 4Gi
      - name: 'replica.persistence.size'
        value: 4Gi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
